### ISSUE TITLE
Login With Snapchat Button Crashes App

### ISSUE THREAD

**Issue by TimmyRB** [sukhkmr19/flutter_snapchat#1]
I have a button in my flutter application that calls the `SnapchatFlutterPlugin.snapchatLogin`, but whenever it's called, it redirects to Snapchat like it should and shows the proper info on Snapchat but crashes my app in the background. My app always crashes with
```
E/AndroidRuntime(19055): FATAL EXCEPTION: OkHttp Dispatcher
E/AndroidRuntime(19055): Process: com.company.app, PID: 19055
E/AndroidRuntime(19055): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
E/AndroidRuntime(19055): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
E/AndroidRuntime(19055): 	at com.google.gson.Gson.fromJson(Gson.java:927)
E/AndroidRuntime(19055): 	at com.google.gson.Gson.fromJson(Gson.java:865)
E/AndroidRuntime(19055): 	at com.snapchat.kit.sdk.core.networking.e.intercept(SourceFile:85)
E/AndroidRuntime(19055): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/AndroidRuntime(19055): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/AndroidRuntime(19055): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
E/AndroidRuntime(19055): 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
E/AndroidRuntime(19055): 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
E/AndroidRuntime(19055): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(19055): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(19055): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(19055): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
E/AndroidRuntime(19055): 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
E/AndroidRuntime(19055): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
E/AndroidRuntime(19055): 	... 11 more
I/Process (19055): Sending signal. PID: 19055 SIG: 9
```
Everything is setup per the ReadMe.md (With fixes to some typos), Snapchat shows my app information correctly, and when it tries to redirect back to my app, my app crashes again. Any help would be much appreciated.

**Comment by TimmyRB** [comment]
Figured it out, you have to use your
`CLIENT ID FOR NON-CONFIDENTIAL OAUTH2 FLOW`
token instead of your
`CLIENT ID FOR CONFIDENTIAL OAUTH2 FLOW`
token
